using System;
using System.Collections.Generic;

namespace SabberStoneCore.Collections
{
	/// <summary>
	/// Interface of all sets which store the insertion order of elements.
	/// Elements are also able to retrievable by index.
	/// </summary>
	/// <typeparam name="T"></typeparam>
	/// <seealso cref="System.Collections.Generic.ISet{T}" />
	/// <seealso cref="System.Collections.Generic.IList{T}" />
	/// <autogeneratedoc />
	public interface IOrderedSet<T>: ISet<T>, IList<T>
	{
		/// <summary>Builds a readonly ordered set from the elements of the current set.</summary>
		/// <returns></returns>
		/// <autogeneratedoc />
		IReadOnlyOrderedSet<T> AsReadOnly();

		/// <summary>Executes the specified lambda on each of the elements of the set.</summary>
		/// <param name="lambda">The lambda.</param>
		void ForEach(Action<T> lambda);
    }
}
