using System;
using System.Collections.Generic;
using System.Linq;

namespace SabberStoneCore.Collections
{
	/// <summary>
	/// Interface of all sets which store the insertion order of elements.
	/// Elements are also able to retrievable by index.
	/// </summary>
	/// <typeparam name="T"></typeparam>
	/// <seealso cref="System.Collections.Generic.ISet{T}" />
	/// <seealso cref="System.Collections.Generic.IList{T}" />
	/// <seealso cref="System.Linq.IOrderedEnumerable{T}"/>
	/// <autogeneratedoc />
	public interface IOrderedSet<T> : ISet<T>, IList<T>, IOrderedEnumerable<T>
	{
		/// <summary>Builds a readonly ordered set from the elements of the current set.</summary>
		/// <returns></returns>
		/// <autogeneratedoc />
		IReadOnlyOrderedSet<T> AsReadOnly();

		/// <summary>Executes the specified lambda on each of the elements of the set.</summary>
		/// <param name="lambda">The action lambda.</param>
		void ForEach(Action<T> lambda);

		/// <summary>Checks if there is an item in the set for which the lambda returns true.</summary>
		/// <param name="lambda">The lambda.</param>
		/// <returns></returns>
		bool Exists(Func<T, bool> lambda);
	}
}
