using System.Collections.Generic;
using System.Linq;

namespace SabberStoneCore.Collections
{
	/// <summary>
	/// A readonly interface for collections which inhibit unique item constraints.
	/// </summary>
	/// <typeparam name="T"></typeparam>
	/// <seealso cref="System.Collections.Generic.IReadOnlyList{T}" />
	/// <seealso cref="SabberStoneCore.Collections.IReadOnlySet{T}" />
	/// <seealso cref="System.Linq.IOrderedEnumerable{T}"/>
	/// <autogeneratedoc />
	public interface IReadOnlyOrderedSet<T>: IReadOnlyList<T>, IReadOnlySet<T>, IOrderedEnumerable<T>
    {
    }
}
