using System.Collections.Generic;

namespace SabberStoneCore.Collections
{
	/// <summary>
	/// A readonly interface for collections which inhibit unique item constraints.
	/// </summary>
	/// <typeparam name="T"></typeparam>
	/// <seealso cref="System.Collections.Generic.IReadOnlyList{T}" />
	/// <seealso cref="SabberStoneCore.Collections.IReadOnlySet{T}" />
	/// <autogeneratedoc />
	public interface IReadOnlyOrderedSet<T>: IReadOnlyList<T>, IReadOnlySet<T>
    {
    }
}
