using SabberStoneCore.Enums;

namespace SabberStoneCore.Model.Zones
{
	/// <summary>
	/// This zone holds all minions played by the controller.
	/// Minions are created from the <see cref="IPlayable"/> <see cref="Card"/> entities.
	/// These entities come from <see cref="HandZone"/>.
	/// </summary>
	/// <seealso cref="SabberStoneCore.Model.Zones.Zone{SabberStoneCore.Model.Minion}" />
	public class BoardZone : Zone<Minion>
	{
		/// <summary><see cref="IZone.MaxSize"/></summary>
		public override int MaxSize => Game.MaxMinionsOnBoard;

		/// <summary>Initializes a new instance of the <see cref="BoardZone"/> class.</summary>
		/// <param name="game">The game which contains the zone.</param>
		/// <param name="controller">The controller which owns the zone.</param>
		/// <param name="type">The kind of zone.</param>
		/// <autogeneratedoc />
		public BoardZone(Game game, Controller controller, EZone type) : base(game, controller, type)
		{
		}
	}
}
