using SabberStoneCore.Enums;
using SabberStoneCore.Model.Entities;
using SabberStoneCore.Model.Entities.Playables;

namespace SabberStoneCore.Model.Zones
{
	/// <summary>
	/// This zone holds all entities which were once played from <see cref="EZone.HAND"/> zone.
	/// </summary>
	/// <seealso cref="SabberStoneCore.Model.Zones.Zone{SabberStoneCore.Model.IPlayable}" />
	public class GraveyardZone : Zone<IPlayable>
	{
		/// <summary>Initializes a new instance of the <see cref="GraveyardZone"/> class.</summary>
		/// <param name="game">The game which contains the zone.</param>
		/// <param name="controller">The controller which owns the zone.</param>
		/// <param name="type">The kind of zone.</param>
		/// <autogeneratedoc />
		public GraveyardZone(Game game, Controller controller, EZone type) : base(game, controller, type)
		{
		}
	}
}
