using SabberStoneCore.Enums;

namespace SabberStoneCore.Model.Zones
{
	/// <summary>
	/// This zone holds all spells (secrets) played the controller.
	/// These spells were generated from the <see cref="IPlayable"/> <see cref="Card"/> entities.
	/// These entities come from <see cref="HandZone"/>.
	/// </summary>
	/// <seealso cref="SabberStoneCore.Model.Zones.Zone{SabberStoneCore.Model.Spell}" />
	public class SecretZone : Zone<Spell>
	{
		/// <summary><see cref="IZone.MaxSize"/> </summary>
		public override int MaxSize => base.MaxSize;

		/// <summary>Initializes a new instance of the <see cref="SecretZone"/> class.</summary>
		/// <param name="game">The game which contains the zone.</param>
		/// <param name="controller">The controller which owns the zone.</param>
		/// <param name="type">The kind of zone.</param>
		/// <autogeneratedoc />
		public SecretZone(Game game, Controller controller, EZone type) : base(game, controller, type)
		{
		}
	}
}
