using SabberStoneCore.Collections;
using SabberStoneCore.Enchants;
using SabberStoneCore.Enums;
using SabberStoneCore.Exceptions;
using SabberStoneCore.Model.Entities;
using SabberStoneCore.Model.Entities.Playables;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SabberStoneCore.Model.Zones
{
	/// <summary>
	/// Base implementation of IZone.
	/// </summary>
	/// <typeparam name="T"></typeparam>
	/// <seealso cref="IZone" />
	/// <seealso cref="System.Collections.Generic.IEnumerable{T}" />
	/// <autogeneratedoc />
	public abstract class Zone<T> : IZone, IEnumerable<T> where T : IPlayable
	{
		#region PROPERTIES

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

		public Game Game { get; }

		public Controller Controller { get; }

		public EZone Type { get; }

		public virtual int MaxSize { get; } = 9999;

		public bool IsFull => !(Count < MaxSize);

		public bool IsEmpty => Count == 0;

		public int Count => _entitiesAsList.Count;

		public T Random => Util.Choose(_entitiesAsList);

		private readonly List<T> _entitiesAsList = new List<T>();

		public IList<Enchant> Enchants { get; } = new List<Enchant>();

		public IList<Trigger> Triggers { get; } = new List<Trigger>();

		public IReadOnlyOrderedSet<IPlayable> GetAll
		{
			get
			{
				return LightWeightOrderedSet<IPlayable>.Build(_entitiesAsList.Cast<IPlayable>());
			}
		}

		public IPlayable this[int zonePosition]
		   => zonePosition >= 0 && zonePosition < _entitiesAsList.Count ? _entitiesAsList[zonePosition] : default(T);

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

		#endregion

		/// <summary>Builds a new zone object.</summary>
		/// <param name="game">The game which contains the zone.</param>
		/// <param name="controller">The controller which owns the zone.</param>
		/// <param name="type">The kind of zone.</param>
		public Zone(Game game, Controller controller, EZone type)
		{
			Game = game;
			Controller = controller;
			Type = type;
			Game.Log(ELogLevel.VERBOSE, EBlockType.PLAY, "Zone", $"Created Zone {type} in Game with Controller {controller.Name}");
		}

		#region IZONE_IMPLEMENTATION

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

		public IPlayable Add(IPlayable entity, int zonePosition = -1)
		{
			if (zonePosition > _entitiesAsList.Count)
			{
				throw new ZoneException("Zoneposition '" + zonePosition + "' isn't in a valid range.");
			}

			// reset the card if it gets into the graveyard ...
			if (Type == EZone.GRAVEYARD)
				entity.Reset();

			MoveTo(entity, zonePosition < 0 ? _entitiesAsList.Count : zonePosition);
			Game.Log(ELogLevel.DEBUG, EBlockType.PLAY, "Zone", $"Entity '{entity} ({entity.Card.Type})' has been added to zone '{Type}' in position '{entity.ZonePosition}'.");

			// activate all zone changing enchantments
			entity.ApplyEnchantments(EEnchantmentActivation.SETASIDE, EZone.SETASIDE);
			entity.ApplyEnchantments(EEnchantmentActivation.BOARD, EZone.PLAY);
			entity.ApplyEnchantments(EEnchantmentActivation.HAND, EZone.HAND);
			entity.ApplyEnchantments(EEnchantmentActivation.DECK, EZone.DECK);

			entity.SetOrderOfPlay(entity.Card.Type);
			return entity;
		}

		public IPlayable Remove(IPlayable entity)
		{
			if (!_entitiesAsList.Remove((T)entity))
			{
				throw new ZoneException("Couldn't remove entity from zone.");
			}
			RePosition(entity.ZonePosition);
			entity.Zone = null;
			//entity[GameTag.ZONE] = (int) Zone.INVALID;
			//entity.ZonePosition = 0;
			return entity;
		}

		public void MoveTo(IPlayable entity, int zonePosition)
		{
			_entitiesAsList.Insert(zonePosition, (T)entity);
			entity.Zone = this;
			entity[EGameTag.ZONE] = (int)Type;
			RePosition(zonePosition);
		}

		public IPlayable Replace(IPlayable oldEntity, IPlayable newEntity)
		{
			MoveTo(newEntity, _entitiesAsList.Count);
			Swap(oldEntity, newEntity);
			return Remove(oldEntity);
		}

		public void Swap(IPlayable oldEntity, IPlayable newEntity)
		{
			if (oldEntity.Zone != newEntity.Zone)
			{
				throw new ZoneException("Swap not possible because of zone missmatch.");
			}

			int oldPos = oldEntity.ZonePosition;
			int newPos = newEntity.ZonePosition;
			newEntity.ZonePosition = oldPos;
			oldEntity.ZonePosition = newPos;
			_entitiesAsList[newPos] = (T)oldEntity;
			_entitiesAsList[oldPos] = (T)newEntity;
		}

		private void RePosition(int zonePosition = 0)
		{
			for (int i = zonePosition; i < _entitiesAsList.Count; i++)
			{
				_entitiesAsList[i].ZonePosition = i;
			}
		}

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
		#endregion

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

		public override string ToString()
		{
			return $"[ZONE {Type} '{Controller.Name}']";
		}

		public IEnumerator<T> GetEnumerator()
		{
			return _entitiesAsList.GetEnumerator();
		}

		IEnumerator IEnumerable.GetEnumerator()
		{
			return GetEnumerator();
		}

		public string FullPrint()
		{
			var str = new StringBuilder();
			str.Append($"{this}|");
			_entitiesAsList.ForEach(p =>
			{
				var m = p as Minion;
				var w = p as Weapon;
				string mStr = m != null ? $"[{m.AttackDamage}/{m.Health}]" : (w != null ? $"[{w.AttackDamage}/{w.Durability}]" : "");
				str.Append($"[P{p.ZonePosition}]{mStr}[C{p.Cost}]{p}|");
			});
			str.Append($"[ENCH {Enchants.Count}]");
			str.Append($"[TRIG {Triggers.Count}]");
			return str.ToString();
		}

		public void Stamp(IZone zone)
		{
			zone.GetAll.ToList().ForEach(p =>
			{
				IPlayable copy = Entity.FromCard(Controller, p.Card, null, null, p.Id);
				copy.Stamp(p as Entity);
				MoveTo(copy, copy.ZonePosition);
			});
			zone.Enchants.ForEach(p => Enchants.Add(p.Copy(p.SourceId, Game, p.Turn, Enchants, p.Owner, p.RemoveTriggers)));
			zone.Triggers.ForEach(p => Triggers.Add(p.Copy(p.SourceId, Game, p.Turn, Triggers, p.Owner)));
		}

		public string Hash(params EGameTag[] ignore)
		{
			var str = new StringBuilder();
			str.Append("[Z:");
			str.Append($"{Type}");
			str.Append("][E:");
			IOrderedEnumerable<IPlayable> list = GetAll;
			if (Type != EZone.PLAY)
			{
				list = list.OrderBy(p => p.Id);
				Array.Resize(ref ignore, ignore.Length + 1);
				ignore[ignore.Length - 1] = EGameTag.ZONE_POSITION;
			}
			list.ForEach(p => str.Append(p.Hash(ignore)));
			str.Append($"][EN:{Enchants.Count}");
			Enchants.ForEach(p => str.Append(p.Hash));
			str.Append($"][TR:{Triggers.Count}");
			Triggers.ForEach(p => str.Append(p.Hash));
			str.Append("]");
			return str.ToString();
		}

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
	}
}