#region copyright
// SabberStone, Hearthstone Simulator in C# .NET Core
// Copyright (C) 2017-2019 SabberStone Team, darkfriend77 & rnilva
//
// SabberStone is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License.
// SabberStone is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
#endregion
using System;

namespace SabberStoneCore.Exceptions
{
	/// <summary>
	/// General exception used within the library.
	/// </summary>
	/// <seealso cref="Exception" />
	public abstract class SabberStoneExceptions : Exception
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
	{
		protected SabberStoneExceptions() { }

		protected SabberStoneExceptions(string message) : base(message) { }

		protected SabberStoneExceptions(string message, Exception innerException) : base(message, innerException) { }
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

	/// <summary>
	/// TODO
	/// </summary>
	/// <seealso cref="SabberStoneExceptions" />
	/// <autogeneratedoc />
	public class GameException : SabberStoneExceptions
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
	{
		public GameException() { }

		public GameException(string message) : base(message) { }

		public GameException(string message, Exception innerException) : base(message, innerException) { }
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

	/// <summary>
	/// TODO
	/// </summary>
	/// <seealso cref="SabberStoneCore.Exceptions.SabberStoneExceptions" />
	/// <autogeneratedoc />
	public class ZoneException : SabberStoneExceptions
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
	{
		public ZoneException() { }

		public ZoneException(string message) : base(message) { }

		public ZoneException(string message, Exception innerException) : base(message, innerException) { }
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

	/// <summary>
	/// TODO
	/// </summary>
	/// <seealso cref="SabberStoneCore.Exceptions.SabberStoneExceptions" />
	/// <autogeneratedoc />
	public class ControllerException : SabberStoneExceptions
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
	{
		public ControllerException() { }

		public ControllerException(string message) : base(message) { }

		public ControllerException(string message, Exception innerException) : base(message, innerException) { }
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

	/// <summary>
	/// TODO
	/// </summary>
	/// <seealso cref="SabberStoneCore.Exceptions.SabberStoneExceptions" />
	/// <autogeneratedoc />
	public class EntityException : SabberStoneExceptions
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
	{
		public EntityException() { }

		public EntityException(string message) : base(message) { }

		public EntityException(string message, Exception innerException) : base(message, innerException) { }
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

	/// <summary>
	/// TODO
	/// </summary>
	/// <seealso cref="SabberStoneCore.Exceptions.SabberStoneExceptions" />
	/// <autogeneratedoc />
	public class EnchantException : SabberStoneExceptions
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
	{
		public EnchantException() { }

		public EnchantException(string message) : base(message) { }

		public EnchantException(string message, Exception innerException) : base(message, innerException) { }
	}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

	public class TaskException : SabberStoneExceptions
	{
		public TaskException() : base() { }

		public TaskException(string message) : base(message) { }

		public TaskException(string message, Exception innerException) : base(message, innerException) { }
	}
}
