//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabberStone.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SabberStone.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [
        ///  {
        ///    &quot;AssetId&quot;: 2539,
        ///    &quot;Id&quot;: &quot;AT_001&quot;,
        ///    &quot;Name&quot;: &quot;Flame Lance&quot;,
        ///    &quot;Text&quot;: &quot;Deal $8 damage to a minion. *spelldmg&quot;,
        ///    &quot;Entourage&quot;: [],
        ///    &quot;Tags&quot;: {
        ///      &quot;COST&quot;: 5,
        ///      &quot;CARD_SET&quot;: 15,
        ///      &quot;CLASS&quot;: 4,
        ///      &quot;CARDTYPE&quot;: 5,
        ///      &quot;RARITY&quot;: 1,
        ///      &quot;COLLECTIBLE&quot;: 1
        ///    },
        ///    &quot;RefTags&quot;: {},
        ///    &quot;Requirements&quot;: {
        ///      &quot;REQ_MINION_TARGET&quot;: 0,
        ///      &quot;REQ_TARGET_TO_PLAY&quot;: 0
        ///    },
        ///    &quot;Collectible&quot;: true,
        ///    &quot;Class&quot;: 4,
        ///    &quot;Race&quot;: 0,
        ///    &quot;Faction&quot;: 0,
        ///    &quot;HasCombo&quot;: f [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string cardDataJson {
            get {
                return ResourceManager.GetString("cardDataJson", resourceCulture);
            }
        }
    }
}
